---
font: "Roboto Mono for Powerline"
fontsize: 12
iconfont: "Material Design Icons"
iconpath: "/usr/share/icons/Adwaita"
barheight: 22
base16_scheme_name: "ashes"
# "base16_scheme":
#   "base00": "1C2023" # ----
#   "base01": "393F45" # ---
#   "base02": "565E65" # --
#   "base03": "747C84" # -
#   "base04": "ADB3BA" # +
#   "base05": "C7CCD1" # ++
#   "base06": "DFE2E5" # +++
#   "base07": "F3F4F5" # ++++
#   "base08": "C7AE95" # orange
#   "base09": "C7C795" # yellow
#   "base0A": "AEC795" # poison green
#   "base0B": "95C7AE" # turquois
#   "base0C": "95AEC7" # aqua
#   "base0D": "AE95C7" # purple
#   "base0E": "C795AE" # pink
#   "base0F": "C79595" # light red
layout:
  border_width: 2
  border_focus: "base08"
widget:
  foreground: "base01"
  background: "panel_bg"
powerline_separator:
  - "\uE0B2"
  - "\uE0B0"
  # - "\uE0BA"
  # - "\uE0B8"
  # - "\uE0BE"
  # - "\uE0BC"
logofont: "font-logos"
logo: "\uF103"  # Arch logo
powerline_color_repeat:
  function: cycle
  indices:
    - 0
    - 3
# powerline_color_repeat: false
